import { supabase } from "@/lib/supabase"
export interface Expense {id:string;farmId:string;farmName:string;date:string;category:string;activity:string;concept:string;currency:"ARS"|"USD";amount:number;source:string;status:string;receipt:string|null;notes:string|null;supplierName:string|null}
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
const relationName=(value:{name:string}|{name:string}[]|null)=>Array.isArray(value)?value[0]?.name??null:value?.name??null
export const administrationService={
 async list(farmId?:string|null):Promise<Expense[]>{let query=client().from("expenses").select("id,farm_id,expense_date,category,activity,concept,currency,amount,source,status,receipt_number,notes,farms(name),suppliers(name)").order("expense_date",{ascending:false});if(farmId)query=query.eq("farm_id",farmId);const{data,error}=await query;if(error)throw error;return(data??[]).map(row=>({id:row.id,farmId:row.farm_id,farmName:relationName(row.farms)??"—",date:row.expense_date,category:row.category,activity:row.activity,concept:row.concept,currency:row.currency,amount:Number(row.amount),source:row.source,status:row.status,receipt:row.receipt_number,notes:row.notes,supplierName:relationName(row.suppliers)}))},
 async create(input:{farmId:string;date:string;category:string;activity?:string;concept:string;currency:string;amount:number;source:string;receipt?:string;notes?:string}){const user=await client().auth.getUser();if(!user.data.user)throw new Error("Sesión inválida.");const campaign=await client().from("campaigns").select("id").eq("farm_id",input.farmId).lte("starts_on",input.date).gte("ends_on",input.date).limit(1).single();if(campaign.error)throw campaign.error;const activity=input.activity??(input.category==="Agricultura"?"agricultura":input.category==="Sanidad"?"ganaderia":"general");const{error}=await client().from("expenses").insert({farm_id:input.farmId,campaign_id:campaign.data.id,expense_date:input.date,category:input.category,activity,concept:input.concept,currency:input.currency,amount:input.amount,source:input.source,receipt_number:input.receipt||null,notes:input.notes||null,created_by:user.data.user.id});if(error)throw error},
 async review(id:string,status:"aprobado"|"observado"|"anulado",notes?:string){const{error}=await client().rpc("review_expense",{p_expense_id:id,p_status:status,p_notes:notes??null});if(error)throw error}
}
