import{supabase}from"@/lib/supabase";
export interface CropCycle{id:string;farmId:string;farmName:string;lotId:string;lotName:string;crop:string;variety:string|null;sownHa:number;harvestedHa:number;sowingDate:string|null;harvestDate:string|null;targetYield:number;actualYield:number;produced:number;sold:number;feed:number;stock:number;referencePrice:number;status:string;revenue:number;cost:number;margin:number;marginHa:number;costHa:number}
export interface LotOption{id:string;name:string;hectares:number}
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
export const agricultureService={
 async list(farmId?:string|null):Promise<CropCycle[]>{let campaignQuery=client().from("campaigns").select("id").eq("active",true);if(farmId)campaignQuery=campaignQuery.eq("farm_id",farmId);const campaignResult=await campaignQuery;if(campaignResult.error)throw campaignResult.error;const ids=(campaignResult.data??[]).map(c=>c.id);if(!ids.length)return[];let q=client().from("agricultural_cycle_performance").select("*").in("campaign_id",ids).order("farm_name").order("lot_name");if(farmId)q=q.eq("farm_id",farmId);const{data,error}=await q;if(error)throw error;return(data??[]).map(r=>({id:r.id,farmId:r.farm_id,farmName:r.farm_name,lotId:r.lot_id,lotName:r.lot_name,crop:r.crop,variety:r.variety,sownHa:Number(r.sown_hectares),harvestedHa:Number(r.harvested_hectares),sowingDate:r.sowing_date,harvestDate:r.harvest_date,targetYield:Number(r.target_yield_kg_ha),actualYield:Number(r.actual_yield_kg_ha),produced:Number(r.produced_tons),sold:Number(r.sold_tons),feed:Number(r.livestock_feed_tons),stock:Number(r.stock_tons),referencePrice:Number(r.reference_price_ars_ton),status:r.status,revenue:Number(r.sales_revenue_ars),cost:Number(r.direct_cost_ars),margin:Number(r.gross_margin_ars),marginHa:Number(r.margin_per_ha_ars),costHa:Number(r.cost_per_ha_ars)}))},
 async lots(farmId:string):Promise<LotOption[]>{const{data,error}=await client().from("lots").select("id,name,hectares").eq("farm_id",farmId).eq("active",true).order("name");if(error)throw error;return(data??[]).map(x=>({id:x.id,name:x.name,hectares:Number(x.hectares)}))},
 async create(input:{farmId:string;lotId:string;crop:string;variety?:string;sownHa:number;sowingDate?:string;targetYield:number;referencePrice:number;status:string}){const user=await client().auth.getUser();if(!user.data.user)throw new Error("Sesión inválida.");const campaign=await client().from("campaigns").select("id").eq("farm_id",input.farmId).eq("active",true).limit(1).single();if(campaign.error)throw campaign.error;const{error}=await client().from("agricultural_cycles").insert({farm_id:input.farmId,campaign_id:campaign.data.id,lot_id:input.lotId,crop:input.crop,variety:input.variety||null,sown_hectares:input.sownHa,sowing_date:input.sowingDate||null,target_yield_kg_ha:input.targetYield,reference_price_ars_ton:input.referencePrice,status:input.status,created_by:user.data.user.id});if(error)throw error},
 async updateProduction(id:string,input:{harvestedHa:number;harvestDate?:string;produced:number;sold:number;feed:number;other:number;referencePrice:number;status:string}){const{error}=await client().from("agricultural_cycles").update({harvested_hectares:input.harvestedHa,harvest_date:input.harvestDate||null,produced_tons:input.produced,sold_tons:input.sold,livestock_feed_tons:input.feed,other_use_tons:input.other,reference_price_ars_ton:input.referencePrice,status:input.status,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error}
}
