import { supabase } from "@/lib/supabase"
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
export interface PerformanceInput{id:string;farmId:string;farmName:string;campaignName:string;hectares:number;opening:number;closing:number;purchases:number;sales:number;targetKg:number;targetMargin:number}
export interface Valuation{id:string;farmName:string;categoryId:string;categoryName:string;date:string;price:number}
export interface WorkType{id:string;name:string;activity:"agricultura"|"ganaderia"|"general";rate:number;description:string|null;active:boolean}
export interface LotConfig{id:string;farmId:string;farmName:string;name:string;hectares:number;currentUse:string;active:boolean}
export interface UserConfig{id:string;name:string;email:string;role:string;active:boolean;farmCount:number;farmIds:string[]}
export const configurationService={
 async updateFarmColor(id:string,color:string){const{error}=await client().from("farms").update({color}).eq("id",id);if(error)throw error},
 async listPerformance():Promise<PerformanceInput[]>{const{data,error}=await client().from("campaign_performance").select("id,farm_id,productive_hectares,opening_weight_kg,closing_weight_kg,purchases_weight_kg,sales_weight_kg,target_kg_ha,target_margin_ha_ars,farms(name),campaigns(name)").order("farm_id");if(error)throw error;return(data??[]).map(row=>{const farm=Array.isArray(row.farms)?row.farms[0]:row.farms,campaign=Array.isArray(row.campaigns)?row.campaigns[0]:row.campaigns;return{id:row.id,farmId:row.farm_id,farmName:farm?.name??"—",campaignName:campaign?.name??"—",hectares:Number(row.productive_hectares),opening:Number(row.opening_weight_kg),closing:Number(row.closing_weight_kg),purchases:Number(row.purchases_weight_kg),sales:Number(row.sales_weight_kg),targetKg:Number(row.target_kg_ha),targetMargin:Number(row.target_margin_ha_ars)}})},
 async updatePerformance(row:PerformanceInput){const{error}=await client().from("campaign_performance").update({productive_hectares:row.hectares,opening_weight_kg:row.opening,closing_weight_kg:row.closing,purchases_weight_kg:row.purchases,sales_weight_kg:row.sales,target_kg_ha:row.targetKg,target_margin_ha_ars:row.targetMargin,updated_at:new Date().toISOString()}).eq("id",row.id);if(error)throw error},
 async listValuations():Promise<Valuation[]>{const{data,error}=await client().from("category_valuations").select("id,category_id,valuation_date,price_per_kg_ars,farms(name),livestock_categories(name)").order("valuation_date",{ascending:false});if(error)throw error;return(data??[]).map(row=>{const farm=Array.isArray(row.farms)?row.farms[0]:row.farms;const category=Array.isArray(row.livestock_categories)?row.livestock_categories[0]:row.livestock_categories;return{id:row.id,farmName:farm?.name??"—",categoryId:row.category_id,categoryName:category?.name??"—",date:row.valuation_date,price:Number(row.price_per_kg_ars)}})},
 async listWorkTypes():Promise<WorkType[]>{const{data,error}=await client().from("work_type_catalog").select("id,name,activity,default_rate_ars_ha,description,active").order("activity").order("name");if(error)throw error;return(data??[]).map(x=>({id:x.id,name:x.name,activity:x.activity,rate:Number(x.default_rate_ars_ha),description:x.description,active:x.active}))},
 async saveWorkType(input:Partial<WorkType>&{name:string;activity:string;rate:number}){const user=await client().auth.getUser();if(!user.data.user)throw new Error("Sesión inválida.");const payload={name:input.name,activity:input.activity,default_rate_ars_ha:input.rate,description:input.description||null,active:input.active??true,updated_at:new Date().toISOString()};const{error}=input.id?await client().from("work_type_catalog").update(payload).eq("id",input.id):await client().from("work_type_catalog").insert({...payload,created_by:user.data.user.id});if(error)throw error},
 async listLots():Promise<LotConfig[]>{const{data,error}=await client().from("lots").select("id,farm_id,name,hectares,current_use,active,farms(name)").order("farm_id").order("name");if(error)throw error;return(data??[]).map(x=>{const farm=Array.isArray(x.farms)?x.farms[0]:x.farms;return{id:x.id,farmId:x.farm_id,farmName:farm?.name??"—",name:x.name,hectares:Number(x.hectares),currentUse:x.current_use??"",active:x.active}})},
 async saveLot(input:Partial<LotConfig>&{farmId:string;name:string;hectares:number;currentUse:string}){const payload={farm_id:input.farmId,name:input.name,hectares:input.hectares,current_use:input.currentUse||null,active:input.active??true,updated_at:new Date().toISOString()};const{error}=input.id?await client().from("lots").update(payload).eq("id",input.id):await client().from("lots").insert(payload);if(error)throw error},
 async updateFarm(id:string,input:{name:string;locality:string;serviceMode:string;color:string}){const{error}=await client().from("farms").update({name:input.name,locality:input.locality,service_mode:input.serviceMode,color:input.color,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error},
 async listUsers():Promise<UserConfig[]>{const{data,error}=await client().from("profiles").select("id,full_name,email,role,active,farm_user_assignments(farm_id)").order("full_name");if(error)throw error;return(data??[]).map(x=>({id:x.id,name:x.full_name,email:x.email,role:x.role,active:x.active,farmCount:x.farm_user_assignments?.length??0,farmIds:(x.farm_user_assignments??[]).map(a=>a.farm_id)}))},
 async updateUser(id:string,role:string,active:boolean){const{error}=await client().from("profiles").update({role,active,updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error},
 async valuationOptions(){const[farms,categories]=await Promise.all([client().from("farms").select("id,name").eq("active",true).order("name"),client().from("livestock_categories").select("id,name").order("name")]);if(farms.error)throw farms.error;if(categories.error)throw categories.error;return{farms:farms.data??[],categories:categories.data??[]}},
 async setGlobalValuation(input:{categoryId:string;date:string;price:number}){const{error}=await client().rpc("set_global_category_valuation",{p_category_id:input.categoryId,p_date:input.date,p_price:input.price});if(error)throw error}
}
