import { supabase } from "@/lib/supabase"
export interface HealthEvent { id:string; farmId:string; farmName:string; title:string; type:string; scheduledOn:string; performedOn:string|null; status:string; animalCount:number|null; product:string|null; dose:string|null; notes:string|null }
export interface ReproductiveEvent { id:string; farmId:string; farmName:string; type:string; eventDate:string; animalCount:number|null; result:string|null; notes:string|null }
export interface HealthTarget { id:string; name:string; animalCount:number }
export interface HealthAnimal { id:string; tagNumber:string; electronicId:string|null }
export interface HealthActionType { id:string; name:string; eventType:string; supportsGeneralDose:boolean; supportsIndividualDose:boolean }
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
export const healthService={
 async list(farmId?:string|null){
  let healthQuery=client().from("health_events").select("id,farm_id,title,event_type,scheduled_on,performed_on,status,animal_count,product,dose,notes,farms(name)").order("scheduled_on")
  let reproductionQuery=client().from("reproductive_events").select("id,farm_id,event_type,event_date,animal_count,result,notes,farms(name)").order("event_date",{ascending:false})
  if(farmId){healthQuery=healthQuery.eq("farm_id",farmId);reproductionQuery=reproductionQuery.eq("farm_id",farmId)}
  const [h,r]=await Promise.all([healthQuery,reproductionQuery]);if(h.error)throw h.error;if(r.error)throw r.error
  const farmName=(relation:{name:string}|{name:string}[]|null)=>Array.isArray(relation)?relation[0]?.name??"—":relation?.name??"—"
  let sessionsQuery=client().from("livestock_work_sessions").select("id,farm_id,session_date,title,status,notes,farms(name),livestock_work_session_actions(id,action_type,product,general_dose,dose_unit,notes)").order("session_date",{ascending:false});if(farmId)sessionsQuery=sessionsQuery.eq("farm_id",farmId);const sessions=await sessionsQuery;if(sessions.error)throw sessions.error
  const jornadaHealth=(sessions.data??[]).flatMap(session=>(session.livestock_work_session_actions??[]).map(action=>({id:action.id,farmId:session.farm_id,farmName:farmName(session.farms),title:session.title,type:action.action_type,scheduledOn:session.session_date,performedOn:session.status==="confirmada"?session.session_date:null,status:session.status==="confirmada"?"realizado":session.status,animalCount:null,product:action.product,dose:action.general_dose==null?null:`${action.general_dose} ${action.dose_unit??""}`.trim(),notes:action.notes??session.notes}))) as HealthEvent[]
  const legacy=(h.data??[]).map(row=>({id:row.id,farmId:row.farm_id,farmName:farmName(row.farms),title:row.title,type:row.event_type,scheduledOn:row.scheduled_on,performedOn:row.performed_on,status:row.status,animalCount:row.animal_count,product:row.product,dose:row.dose,notes:row.notes})) as HealthEvent[]
  return {health:[...jornadaHealth,...legacy],reproduction:(r.data??[]).map(row=>({id:row.id,farmId:row.farm_id,farmName:farmName(row.farms),type:row.event_type,eventDate:row.event_date,animalCount:row.animal_count,result:row.result,notes:row.notes})) as ReproductiveEvent[]}
 },
 async targets(farmId:string):Promise<HealthTarget[]>{const{data,error}=await client().from("herds").select("id,name,animals(id)").eq("farm_id",farmId).eq("active",true).order("name");if(error)throw error;return(data??[]).map(h=>({id:h.id,name:h.name,animalCount:h.animals?.length??0}))},
 async actionTypes():Promise<HealthActionType[]>{const{data,error}=await client().from("livestock_action_type_catalog").select("id,name,event_type,supports_general_dose,supports_individual_dose").eq("active",true).order("name");if(error)throw error;return(data??[]).map(row=>({id:row.id,name:row.name,eventType:row.event_type,supportsGeneralDose:row.supports_general_dose,supportsIndividualDose:row.supports_individual_dose}))},
 async animals(farmId:string,herdId?:string):Promise<HealthAnimal[]>{let query=client().from("animals").select("id,tag_number,electronic_id").eq("farm_id",farmId).eq("active",true).order("tag_number");if(herdId)query=query.eq("herd_id",herdId);const{data,error}=await query;if(error)throw error;return(data??[]).map(row=>({id:row.id,tagNumber:row.tag_number,electronicId:row.electronic_id}))},
 async create(input:{farmId:string;herdId?:string;title:string;type:string;actionTypeId?:string;scheduledOn:string;animalCount?:number;product?:string;dose?:string;doseUnit?:string;responsible?:string;notes?:string;individualDoses?:Record<string,string>}){const user=await client().auth.getUser();if(!user.data.user)throw new Error("Sesión inválida.");const session=await client().from("livestock_work_sessions").insert({farm_id:input.farmId,herd_id:input.herdId||null,session_date:input.scheduledOn,session_type:input.type,title:input.title,source:"manual",status:"borrador",notes:input.notes||null,created_by:user.data.user.id}).select("id").single();if(session.error)throw session.error;const numericDose=input.dose?.trim()?Number(input.dose.replace(",",".")):null;if(numericDose!==null&&!Number.isFinite(numericDose))throw new Error("La dosis general debe ser numérica.");const action=await client().from("livestock_work_session_actions").insert({session_id:session.data.id,action_type:input.type,action_type_id:input.actionTypeId||null,source:"manual",product:input.product||null,general_dose:numericDose,dose_unit:input.doseUnit||null,responsible:input.responsible||null,notes:input.notes||null,metadata:{general_dose:true}}).select("id").single();if(action.error)throw action.error;if(input.herdId){const animals=await client().from("animals").select("id").eq("farm_id",input.farmId).eq("herd_id",input.herdId).eq("active",true);if(animals.error)throw animals.error;if(animals.data.length){const participants=await client().from("livestock_work_session_animals").insert(animals.data.map(animal=>({session_id:session.data.id,animal_id:animal.id,metadata:{source:"herd_snapshot"}})));if(participants.error)throw participants.error;const actionAnimals=await client().from("livestock_work_session_action_animals").insert(animals.data.map(animal=>{const raw=input.individualDoses?.[animal.id]?.trim(),individual=raw?Number(raw.replace(",",".")):null;if(individual!==null&&!Number.isFinite(individual))throw new Error("Hay una dosis individual inválida.");return{action_id:action.data.id,animal_id:animal.id,individual_dose:individual,dose_unit:individual===null?null:input.doseUnit||null,metadata:{uses_general_dose:individual===null}}}));if(actionAnimals.error)throw actionAnimals.error}}return session.data.id}
}
