import { supabase } from "@/lib/supabase"

export type Activity = "ganaderia" | "agricultura" | "general"
export interface Sale { id:string; farmId:string; farmName:string; date:string; activity:Activity; product:string; buyer:string; quantity:number; unit:string; unitPrice:number; currency:"ARS"|"USD"; gross:number; net:number; status:string; collected:number; document:string|null }
export interface ActivityMargin { farmId:string; farmName:string; activity:Activity; income:number; collected:number; costs:number; margin:number }
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
const relationName=(value:{name:string}|{name:string}[]|null)=>Array.isArray(value)?value[0]?.name??"—":value?.name??"—"
export const incomeService={
 async list(farmId?:string|null):Promise<Sale[]>{let q=client().from("income_sales").select("id,farm_id,sale_date,activity,product,buyer,quantity,unit,unit_price,currency,gross_amount,net_amount,status,collected_amount,document_number,farms(name)").order("sale_date",{ascending:false});if(farmId)q=q.eq("farm_id",farmId);const{data,error}=await q;if(error)throw error;return(data??[]).map(r=>({id:r.id,farmId:r.farm_id,farmName:relationName(r.farms),date:r.sale_date,activity:r.activity,product:r.product,buyer:r.buyer,quantity:Number(r.quantity),unit:r.unit,unitPrice:Number(r.unit_price),currency:r.currency,gross:Number(r.gross_amount),net:Number(r.net_amount),status:r.status,collected:Number(r.collected_amount),document:r.document_number}))},
 async margins(farmId?:string|null):Promise<ActivityMargin[]>{let q=client().from("farm_activity_margins").select("farm_id,farm_name,activity,income_ars,collected_ars,costs_ars,margin_ars").eq("campaign_name","2026/27").order("farm_name");if(farmId)q=q.eq("farm_id",farmId);const{data,error}=await q;if(error)throw error;return(data??[]).map(r=>({farmId:r.farm_id,farmName:r.farm_name,activity:r.activity,income:Number(r.income_ars),collected:Number(r.collected_ars),costs:Number(r.costs_ars),margin:Number(r.margin_ars)}))},
 async create(input:{farmId:string;date:string;activity:Activity;product:string;buyer:string;quantity:number;unit:string;unitPrice:number;currency:string;exchangeRate:number;commission:number;freight:number;other:number;status:string;collected:number;document?:string}){const user=await client().auth.getUser();if(!user.data.user)throw new Error("Sesión inválida.");const campaigns=await client().from("campaigns").select("id").eq("farm_id",input.farmId).lte("starts_on",input.date).gte("ends_on",input.date).limit(1).single();if(campaigns.error)throw campaigns.error;const{error}=await client().from("income_sales").insert({farm_id:input.farmId,campaign_id:campaigns.data.id,sale_date:input.date,activity:input.activity,product:input.product,buyer:input.buyer,quantity:input.quantity,unit:input.unit,unit_price:input.unitPrice,currency:input.currency,exchange_rate:input.currency==="USD"?input.exchangeRate:1,commission_amount:input.commission,freight_amount:input.freight,other_deductions:input.other,status:input.status,collected_amount:input.collected,document_number:input.document||null,created_by:user.data.user.id});if(error)throw error}
}
