import { supabase } from "@/lib/supabase"
import { parseCsvFile, type ParsedCsv } from "@/features/livestock/import-engine/parser"
import { mapRows, suggestMapping, type ColumnMapping } from "@/features/livestock/import-engine/mapper"
import { validateRows } from "@/features/livestock/import-engine/validator"
import { adaptGallagherAnimalHistory, isGallagherAnimalHistory, type GallagherExternalEvent } from "@/features/livestock/import-engine/gallagher-animal-history"
import { adaptGallagherSessionExport, isGallagherSessionExport } from "@/features/livestock/import-engine/gallagher-session-export"

export type ImportStatus = "NUEVO"|"EXISTENTE"|"ERROR"|"DUPLICADO"|"CONFLICTO"|"REVERTIDO"
export interface AnimalRow { id:string; farmId:string; tagNumber:string; electronicId:string|null; electronicIdRaw:string|null; sex:string|null; breed:string|null; status:string; categoryName:string|null; herdName:string|null; lastEvent:string|null; lastEventDate:string|null }
export interface AnimalEvent { id:string; type:string; date:string; source:string; notes:string|null; metadata:Record<string,unknown> }
export interface GallagherRow { rowNumber:number; tagNumber:string; electronicIdRaw:string; electronicId:string; eventDate:string; draftGroup:string; notes:string; status:ImportStatus|"ACTUALIZAR"; message?:string; animalId?:string; reactivate?:boolean; raw:Record<string,unknown>; detectedEventTypes:string[]; weight:number|null; previousWeight:number|null; bodyConditionScore:number|null; days:number|null; weightGain:number|null; adg:number|null; pregnancyStatus:string; breed:string; sex:string; treatment:string; dose:number|null; doseUnit:string; operator:string; externalEvents:GallagherExternalEvent[]; uninterpretedValues:Array<{field:string;value:string}> }
export interface ParsedLivestockImport { document:ParsedCsv; mapping:ColumnMapping; rows:GallagherRow[]; detectedDate:string|null; format:"animal_history"|"session_export"|"generic"; externalSessions:string[] }
export interface ImportHistory { id:string; filename:string; importedAt:string; total:number; created:number; existing:number; errors:number; status:string }
export interface FilenameContext { categoryName:string; herdName:string; reproductiveStatus:string; calvingSeason:string; detectedCode:string|null; eventType:string; probableDate:string; period:string; keywords:string[]; confidence:"alta"|"media"|"baja" }
export interface FilenameContextDecision { values:FilenameContext; confirmed:Record<"categoryName"|"herdName"|"reproductiveStatus"|"calvingSeason"|"eventType"|"probableDate"|"period",boolean>; original:FilenameContext }

function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
const one=<T,>(value:T|T[]|null):T|null=>Array.isArray(value)?value[0]??null:value
export const normalizeEid=(value:string)=>value.replace(/[^0-9A-Za-z]/g,"").toUpperCase()
export function inferFilenameContext(filename:string):FilenameContext{const base=filename.replace(/\.csv$/i,"").replace(/[_-]+/g," ").trim(),upper=base.toUpperCase(),tokens=upper.split(/\s+/).filter(Boolean),has=(pattern:RegExp)=>pattern.test(upper),dateMatch=filename.match(/\b(20\d{2})[-_](\d{2})[-_](\d{2})\b/),probableDate=dateMatch?`${dateMatch[1]}-${dateMatch[2]}-${dateMatch[3]}`:"",autumn=has(/\bOTO(?:N|Ñ)O\b/),winter=has(/\bINVIERNO\b/),spring=has(/\bPRIMAVERA\b/),summer=has(/\bVERANO\b/),period=autumn?"Otoño":winter?"Invierno":spring?"Primavera":summer?"Verano":tokens.find(x=>/^(ENERO|FEBRERO|MARZO|ABRIL|MAYO|JUNIO|JULIO|AGOSTO|SEPTIEMBRE|OCTUBRE|NOVIEMBRE|DICIEMBRE)$/.test(x))??"",categoryName=has(/\bNOVILLOS?\b/)?"Novillo":has(/\bVAQUILLONAS?\b/)?"Vaquillona":has(/\bVACAS?\b|\bMADRES?\b/)?"Vaca":has(/\bTERNERAS?\b/)?"Ternera":has(/\bTERNEROS?\b/)?"Ternero":"",eventType=has(/\bPESAJE\b/)?"Pesaje":has(/\bTACTO\b/)?"Tacto":has(/\bSERVICIO\b/)?"Servicio":has(/\bDESPARASITACION\b/)?"Desparasitación":has(/\bIDENTIFICACION\b|\bCARAVANAS?\b|\bALTA\b/)?"Identificación":"",herdName=has(/\bNOVILLOS?\b.*\bRECRIA\b/)?"Novillos Recría":has(/\bMADRES?\b.*\bTERNEROS?\b/)?`Ternero${period?` ${period}`:""}`:has(/\bVACAS?\b/)&&period?`Vacas ${period}`:has(/\bVAQUILLONAS?\b.*\bSERVICIO\b/)?"Vaquillonas Servicio":"",reproductiveStatus=eventType==="Tacto"||eventType==="Servicio"?eventType:"",meaningful=[categoryName,herdName,eventType,period,probableDate].filter(Boolean).length;return{categoryName,herdName,reproductiveStatus,calvingSeason:period,detectedCode:tokens.find(x=>/^\d{4}$/.test(x)&&!x.startsWith("20"))??null,eventType,probableDate,period,keywords:tokens.filter(x=>!/^(20\d{2}|\d{4}|\d{2})$/.test(x)),confidence:meaningful>=4?"alta":meaningful>=2?"media":"baja"}}

function csvMatrix(text:string){const rows:string[][]=[];let row:string[]=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(char===','&&!quoted){row.push(cell);cell=""}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=char}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
const aliases:Record<string,string[]>={tagNumber:["tag number","tag","visual id","caravana"],electronicId:["electronic id","eid","rfid"],date:["date","datetime","event date","fecha"],draftGroup:["draft group","group","grupo"],notes:["notes","note","observaciones"],weight:["weight (kg)","weight","peso (kg)","peso"],previousWeight:["previous weight (kg)","previous weight","peso anterior (kg)","peso anterior"],days:["days","días","dias"],weightGain:["weight gain (kg)","weight gain","ganancia (kg)","ganancia"],adg:["adg (kg/day)","adg","gdp (kg/día)","gdp"],treatment:["treatment","tratamiento","product","producto"],dose:["dose","dosis"],doseUnit:["dose unit","unidad dosis"],eventType:["event type","tipo de evento"],operator:["operator","operador","responsable"]}
const findColumn=(headers:string[],key:string)=>headers.findIndex(header=>aliases[key].includes(header.trim().toLowerCase()))
function parseDate(value:string){const text=value.trim();let year="",month="",day="",hour="00",minute="00",second="00";const iso=text.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})(?:[ T]+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(iso){[,year,month,day,hour="00",minute="00",second="00"]=iso}else{const gallagher=text.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2}|\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?$/);if(!gallagher)return "";month=gallagher[1];day=gallagher[2];year=gallagher[3].length===2?`20${gallagher[3]}`:gallagher[3];hour=gallagher[4]??"00";minute=gallagher[5]??"00";second=gallagher[6]??"00"}const numbers=[Number(year),Number(month),Number(day),Number(hour),Number(minute),Number(second)];if(numbers.some(Number.isNaN)||numbers[1]<1||numbers[1]>12||numbers[2]<1||numbers[2]>31||numbers[3]>23||numbers[4]>59||numbers[5]>59)return "";return `${year.padStart(4,"0")}-${month.padStart(2,"0")}-${day.padStart(2,"0")}T${hour.padStart(2,"0")}:${minute}:${second}`}

export async function parseGallagherCsv(file:File,mapping?:ColumnMapping,fallbackDate=""):Promise<ParsedLivestockImport>{
 const document=await parseCsvFile(file),activeMapping=mapping??suggestMapping(document.headers)
 if(isGallagherAnimalHistory(document)){const rows=adaptGallagherAnimalHistory(document).map(row=>({...row,status:"NUEVO" as const,weight:null,previousWeight:null,bodyConditionScore:null,days:null,weightGain:null,adg:null,pregnancyStatus:"",breed:String(row.raw.Breed??""),sex:String(row.raw.Sex??""),treatment:"",dose:null,doseUnit:"",operator:""})),externalSessions=[...new Set(rows.flatMap(row=>row.externalEvents.map(event=>event.externalSessionName).filter((value):value is string=>Boolean(value))))];return{document,mapping:activeMapping,rows,detectedDate:rows.find(row=>row.eventDate)?.eventDate??null,format:"animal_history",externalSessions}}
 if(isGallagherSessionExport(document)){const rows=adaptGallagherSessionExport(document).map(row=>({...row,status:(row.eventDate?"NUEVO":"ERROR") as ImportStatus, message:row.eventDate?undefined:"Fecha u hora inválida",weight:null,previousWeight:null,bodyConditionScore:null,days:null,weightGain:null,adg:null,pregnancyStatus:"",breed:"",sex:"",treatment:"",dose:null,doseUnit:"",operator:""}));return{document,mapping:activeMapping,rows,detectedDate:rows.find(row=>row.eventDate)?.eventDate??null,format:"session_export",externalSessions:[document.filename.replace(/\.csv$/i,"")]}}
 const rows=(validateRows(mapRows(document,activeMapping),fallbackDate) as Omit<GallagherRow,"externalEvents"|"uninterpretedValues">[]).map(row=>({...row,externalEvents:[],uninterpretedValues:[]}))
 return{document,mapping:activeMapping,rows,detectedDate:rows.find(row=>row.eventDate)?.eventDate??null,format:"generic",externalSessions:[]}
}
export function remapLivestockCsv(document:ParsedCsv,mapping:ColumnMapping,fallbackDate=""):GallagherRow[]{if(isGallagherAnimalHistory(document))return adaptGallagherAnimalHistory(document).map(row=>({...row,status:"NUEVO",weight:null,previousWeight:null,bodyConditionScore:null,days:null,weightGain:null,adg:null,pregnancyStatus:"",breed:String(row.raw.Breed??""),sex:String(row.raw.Sex??""),treatment:"",dose:null,doseUnit:"",operator:""})) as GallagherRow[];if(isGallagherSessionExport(document))return adaptGallagherSessionExport(document).map(row=>({...row,status:row.eventDate?"NUEVO":"ERROR",message:row.eventDate?undefined:"Fecha u hora inválida",weight:null,previousWeight:null,bodyConditionScore:null,days:null,weightGain:null,adg:null,pregnancyStatus:"",breed:"",sex:"",treatment:"",dose:null,doseUnit:"",operator:""})) as GallagherRow[];return(validateRows(mapRows(document,mapping),fallbackDate) as Omit<GallagherRow,"externalEvents"|"uninterpretedValues">[]).map(row=>({...row,externalEvents:[],uninterpretedValues:[]}))}

export const livestockRegistryService={
 async animals(farmId?:string|null):Promise<AnimalRow[]>{let query=client().from("animals").select("id,farm_id,tag_number,electronic_id,electronic_id_raw,sex,breed,status,livestock_categories(name),herds(name),animal_events(event_type,event_date)").eq("active",true).is("reverted_at",null).is("animal_events.voided_at",null).order("tag_number");if(farmId)query=query.eq("farm_id",farmId);const{data,error}=await query;if(error)throw error;return(data??[]).map(row=>{const events=[...(row.animal_events??[])].sort((a,b)=>String(b.event_date).localeCompare(String(a.event_date)));return{id:row.id,farmId:row.farm_id,tagNumber:row.tag_number,electronicId:row.electronic_id,electronicIdRaw:row.electronic_id_raw,sex:row.sex,breed:row.breed,status:row.status,categoryName:one(row.livestock_categories)?.name??null,herdName:one(row.herds)?.name??null,lastEvent:events[0]?.event_type??null,lastEventDate:events[0]?.event_date??null}})},
 async events(animalId:string):Promise<AnimalEvent[]>{const{data,error}=await client().from("animal_events").select("id,event_type,event_date,source,notes,metadata").eq("animal_id",animalId).is("voided_at",null).order("event_date",{ascending:false});if(error)throw error;return(data??[]).map(x=>({id:x.id,type:x.event_type,date:x.event_date,source:x.source,notes:x.notes,metadata:x.metadata??{}}))},
 async imports(farmId?:string|null):Promise<ImportHistory[]>{let q=client().from("livestock_imports").select("id,filename,imported_at,total_rows,created_animals,existing_animals,error_rows,status").order("imported_at",{ascending:false}).limit(20);if(farmId)q=q.eq("farm_id",farmId);const{data,error}=await q;if(error)throw error;return(data??[]).map(x=>({id:x.id,filename:x.filename,importedAt:x.imported_at,total:x.total_rows,created:x.created_animals,existing:x.existing_animals,errors:x.error_rows,status:x.status}))},
 async classify(farmId:string,rows:GallagherRow[]):Promise<GallagherRow[]>{const ids=[...new Set(rows.map(r=>r.electronicId).filter(Boolean))];if(!ids.length)return rows;const{data,error}=await client().from("animals").select("electronic_id,tag_number").eq("farm_id",farmId).in("electronic_id",ids);if(error)throw error;const found=new Map((data??[]).map(x=>[x.electronic_id,x.tag_number]));return rows.map(row=>{if(row.status!=="NUEVO")return row;const tag=found.get(row.electronicId);const status:ImportStatus=tag===row.tagNumber||!row.tagNumber?"EXISTENTE":"CONFLICTO";return tag==null?row:{...row,status,message:tag!==row.tagNumber?`El EID ya pertenece a la caravana ${tag}`:undefined}})},
 async duplicateImport(farmId:string,hash:string){const{data,error}=await client().from("livestock_imports").select("id,filename,imported_at").eq("farm_id",farmId).eq("provider","gallagher").eq("file_hash",hash).maybeSingle();if(error)throw error;return data},
 async confirm(farmId:string,file:File,hash:string,rows:GallagherRow[],decision:FilenameContextDecision){const accepted=rows.filter(r=>r.status==="NUEVO"||r.status==="EXISTENTE").map(({raw,status,message,...row})=>row),explicitHerd=rows.some(r=>r.draftGroup.trim()),pick=(key:keyof FilenameContextDecision["confirmed"])=>decision.confirmed[key]?String(decision.values[key]??""):"",applied={categoryName:pick("categoryName"),herdName:explicitHerd?"":pick("herdName"),reproductiveStatus:pick("reproductiveStatus"),calvingSeason:pick("calvingSeason"),eventType:pick("eventType"),probableDate:pick("probableDate"),period:pick("period")},modified=Object.fromEntries(Object.keys(decision.confirmed).filter(key=>decision.confirmed[key as keyof typeof decision.confirmed]&&decision.values[key as keyof FilenameContext]!==decision.original[key as keyof FilenameContext]).map(key=>[key,true]));const{data,error}=await client().rpc("import_livestock_provider_with_work_session",{p_farm_id:farmId,p_provider:"gallagher",p_filename:file.name,p_file_hash:hash,p_rows:accepted,p_category_name:applied.categoryName||null,p_herd_name:applied.herdName||null,p_reproductive_status:applied.reproductiveStatus||null,p_calving_season:applied.calvingSeason||null,p_session_confirmed:decision.confirmed.eventType,p_session_type:applied.eventType||null,p_session_date:applied.probableDate||null,p_period:applied.period||null,p_detected_code:decision.values.detectedCode,p_filename_keywords:decision.original.keywords,p_filename_inferences:decision.original,p_filename_confirmed:applied,p_filename_modified:modified});if(error)throw error;return data}
}
