import { supabase } from "@/lib/supabase"
import type { ParsedCsv } from "@/features/livestock/import-engine/parser"
import type { ColumnMapping } from "@/features/livestock/import-engine/mapper"
import type { GallagherRow,FilenameContextDecision } from "@/services/livestock-registry.service"
export type SessionMode="new"|"existing"|"none"
export interface WorkSessionOption{id:string;date:string;type:string;title:string;status:string}
export interface SessionTypeOption{id:string;name:string;description:string|null}
export interface HerdOption{id:string;name:string}
export interface DraftGroupDecision{mode:"existing"|"create"|"ignore";herd_id?:string;name?:string;confirmed?:boolean;suggested?:boolean}
export interface MappingTemplate{id:string;name:string;signature:string;mapping:ColumnMapping}
export interface ImportConfirmation{farmId:string;provider:string;file:File;document:ParsedCsv;mapping:ColumnMapping;rows:GallagherRow[];filenameDecision:FilenameContextDecision;sessionMode:SessionMode;existingSessionId?:string;sessionType?:string;sessionDate?:string;mappingTemplateId?:string;draftGroupDecisions:Record<string,DraftGroupDecision>}
function client(){if(!supabase)throw new Error("Supabase no está configurado.");return supabase}
export const livestockImportService={
 async duplicateImport(farmId:string,hash:string){const{data,error}=await client().from("livestock_imports").select("id,filename,imported_at,status").eq("farm_id",farmId).eq("provider","gallagher").eq("content_hash",hash).neq("status","revertido").maybeSingle();if(error)throw error;return data},
 async workSessions(farmId:string):Promise<WorkSessionOption[]>{const{data,error}=await client().from("livestock_work_sessions").select("id,session_date,session_type,title,status").eq("farm_id",farmId).neq("status","anulada").order("session_date",{ascending:false});if(error)throw error;return(data??[]).map(x=>({id:x.id,date:x.session_date,type:x.session_type,title:x.title,status:x.status}))},
 async sessionTypes():Promise<SessionTypeOption[]>{const{data,error}=await client().from("livestock_session_type_catalog").select("id,name,description").eq("active",true).order("name");if(error)throw error;return(data??[]) as SessionTypeOption[]},
 async herds(farmId:string):Promise<HerdOption[]>{const{data,error}=await client().from("herds").select("id,name").eq("farm_id",farmId).eq("active",true).order("name");if(error)throw error;return(data??[]) as HerdOption[]},
 async mappingTemplate(provider:string,signature:string):Promise<MappingTemplate|null>{const{data,error}=await client().from("livestock_import_mapping_templates").select("id,name,header_signature,mapping").eq("provider",provider).eq("header_signature",signature).eq("active",true).maybeSingle();if(error)throw error;return data?{id:data.id,name:data.name,signature:data.header_signature,mapping:data.mapping as ColumnMapping}:null},
 async saveMapping(provider:string,name:string,signature:string,headers:string[],mapping:ColumnMapping){const user=await client().auth.getUser();if(!user.data.user)throw new Error("Sesión inválida.");const{data,error}=await client().from("livestock_import_mapping_templates").upsert({provider,name,header_signature:signature,headers,mapping,created_by:user.data.user.id,updated_at:new Date().toISOString()},{onConflict:"provider,header_signature"}).select("id").single();if(error)throw error;return data.id as string},
 async classify(farmId:string,rows:GallagherRow[]):Promise<GallagherRow[]>{const eids=[...new Set(rows.map(r=>r.electronicId).filter(Boolean))],tags=[...new Set(rows.map(r=>r.tagNumber).filter(Boolean))];let query=client().from("animals").select("id,electronic_id,tag_number,sex,breed,status,reverted_at").eq("farm_id",farmId);if(eids.length)query=query.in("electronic_id",eids);else if(tags.length)query=query.in("tag_number",tags);else return rows;const{data,error}=await query;if(error)throw error;const byEid=new Map((data??[]).filter(x=>x.electronic_id).map(x=>[x.electronic_id,x])),byTag=new Map((data??[]).map(x=>[x.tag_number,x]));return rows.map(row=>{if(row.status==="ERROR"||row.status==="DUPLICADO")return row;const found=(row.electronicId&&byEid.get(row.electronicId))||byTag.get(row.tagNumber);if(!found)return row;if(found.reverted_at||found.status==="revertido")return{...row,animalId:found.id,status:"REVERTIDO",message:"Este EID fue revertido. Requiere reactivación explícita."};if(row.electronicId&&found.electronic_id===row.electronicId&&row.tagNumber&&found.tag_number!==row.tagNumber)return{...row,status:"CONFLICTO",message:`El EID pertenece a la caravana ${found.tag_number}`};const masterUpdate=(!found.sex&&row.sex)||(!found.breed&&row.breed);return{...row,animalId:found.id,status:masterUpdate?"ACTUALIZAR":"EXISTENTE"}})},
 async classifyExternalEvents(farmId:string,rows:GallagherRow[]):Promise<GallagherRow[]>{const events=rows.flatMap(row=>row.externalEvents.map(event=>({fingerprint:event.fingerprint,event_type:event.eventType,event_date:event.eventDate,electronic_id:row.electronicId})));if(!events.length)return rows;const{data,error}=await client().rpc("preview_livestock_external_events",{p_farm_id:farmId,p_events:events});if(error)throw error;const existing=new Set((data??[]) as string[]);return rows.map(row=>({...row,externalEvents:row.externalEvents.map(event=>({...event,status:existing.has(event.fingerprint)?"EXISTENTE":"NUEVO"}))}))},
 async confirm(input:ImportConfirmation){const accepted=input.rows.filter(row=>["NUEVO","EXISTENTE","ACTUALIZAR"].includes(row.status)||(row.status==="REVERTIDO"&&row.reactivate)).map(({raw,status,message,animalId,reactivate,...row})=>({...row,externalEvents:row.externalEvents.map(({status:externalStatus,...event})=>event)})),reactivateIds=input.rows.filter(row=>row.status==="REVERTIDO"&&row.reactivate&&row.animalId).map(row=>row.animalId),explicitHerd=input.rows.some(row=>row.draftGroup.trim()),decision=input.filenameDecision,pick=(key:keyof typeof decision.confirmed)=>decision.confirmed[key]?String(decision.values[key]??""):"",applied={categoryName:pick("categoryName"),herdName:explicitHerd?"":pick("herdName"),reproductiveStatus:pick("reproductiveStatus"),calvingSeason:pick("calvingSeason"),eventType:pick("eventType"),probableDate:pick("probableDate"),period:pick("period")},modified=Object.fromEntries(Object.keys(decision.confirmed).filter(key=>decision.confirmed[key as keyof typeof decision.confirmed]&&decision.values[key as keyof typeof decision.values]!==decision.original[key as keyof typeof decision.original]).map(key=>[key,true])),ignored=Object.entries(input.mapping).filter(([,field])=>field==="ignore").map(([header])=>header);const{data,error}=await client().rpc("import_livestock_provider_v3",{p_farm_id:input.farmId,p_provider:input.provider,p_filename:input.file.name,p_file_hash:input.document.hash,p_rows:accepted,p_session_mode:input.sessionMode,p_existing_session_id:input.existingSessionId??null,p_session_type:(input.sessionType??applied.eventType)||null,p_session_date:(input.sessionDate??applied.probableDate)||null,p_category_name:applied.categoryName||null,p_herd_name:applied.herdName||null,p_mapping:input.mapping,p_headers:input.document.headers,p_ignored_headers:ignored,p_mapping_template_id:input.mappingTemplateId??null,p_filename_keywords:decision.original.keywords,p_draft_group_decisions:input.draftGroupDecisions,p_reactivate_animal_ids:reactivateIds,p_filename_inferences:decision.original,p_filename_confirmed:applied,p_filename_modified:modified});if(error)throw error;return data},
 async confirmSession(sessionId:string){const{error}=await client().rpc("confirm_livestock_work_session",{p_session_id:sessionId});if(error)throw error},
 async annul(importId:string,reason:string){const{error}=await client().rpc("annul_livestock_import",{p_import_id:importId,p_reason:reason});if(error)throw error},
 async reversalPreview(importId:string){const{data,error}=await client().rpc("preview_livestock_import_reversal",{p_import_id:importId});if(error)throw error;return data},
 async revert(importId:string,reason:string){const{data,error}=await client().rpc("revert_livestock_import",{p_import_id:importId,p_reason:reason});if(error)throw error;return data}
}
