import { FormEvent, useEffect, useMemo, useState } from "react"
import { Plus, Search, X } from "lucide-react"
import { useFarmScope } from "@/app/providers/FarmScopeProvider"
import { healthService, type HealthEvent, type ReproductiveEvent } from "@/services/health.service"

const fmt = new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "short", year: "numeric" })
const labels: Record<string,string> = { vacunacion:"Vacunación", tratamiento:"Tratamiento", diagnostico:"Diagnóstico", desparasitacion:"Desparasitación", control:"Control", servicio:"Servicio", inseminacion:"Inseminación", tacto:"Tacto", parto:"Parto", destete:"Destete" }

export function HealthPage() {
  const { farms, selectedFarmId, selectedFarm } = useFarmScope()
  const [health,setHealth] = useState<HealthEvent[]>([])
  const [reproduction,setReproduction] = useState<ReproductiveEvent[]>([])
  const [loading,setLoading] = useState(true)
  const [creating,setCreating] = useState(false)
  const [query,setQuery] = useState("")
  const [error,setError] = useState<string|null>(null)
  const load = () => healthService.list(selectedFarmId).then(data => { setHealth(data.health); setReproduction(data.reproduction) }).catch(cause => setError(cause instanceof Error ? cause.message : "No pudimos cargar sanidad.")).finally(()=>setLoading(false))
  useEffect(()=>{setLoading(true);void load()},[selectedFarmId])
  const filtered = useMemo(()=>health.filter(event=>`${event.title} ${event.farmName} ${event.product??""}`.toLowerCase().includes(query.toLowerCase())),[health,query])
  if(error)return <section className="page"><div className="data-error"><strong>No pudimos cargar Sanidad</strong><span>{error}</span></div></section>
  if(loading)return <section className="page"><div className="loading-panel">Cargando agenda sanitaria…</div></section>
  return <section className="page">
    <div className="page-heading"><div><span className="eyebrow">{selectedFarm?.name.toUpperCase()??"TODOS LOS CAMPOS"}</span><h1>Sanidad y reproducción</h1><p>Agenda preventiva, tratamientos y resultados reproductivos.</p></div><button className="primary-button" onClick={()=>setCreating(true)}><Plus size={17}/> Nueva actividad</button></div>
    <div className="record-summary"><span><strong>{health.filter(item=>item.status==="pendiente").length}</strong> pendientes</span><span><strong>{health.filter(item=>item.status==="realizado").length}</strong> realizadas</span><span><strong>{reproduction.length}</strong> eventos reproductivos</span></div>
    <div className="toolbar"><div className="search"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar actividad, campo o producto" aria-label="Buscar actividades sanitarias"/></div><select aria-label="Filtrar estado"><option>Todos los estados</option><option>Pendientes</option><option>Realizadas</option></select></div>
    <section className="table-section"><div className="table-section-heading"><div><span className="eyebrow">AGENDA SANITARIA</span><h2>Actividades y tratamientos</h2></div><span>{filtered.length} registros</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Actividad</th><th>Campo</th><th>Tipo</th><th>Producto / dosis</th><th>Animales</th><th>Estado</th></tr></thead><tbody>{filtered.map(event=><tr key={event.id}><td>{fmt.format(new Date(`${event.scheduledOn}T12:00:00`))}</td><td><strong>{event.title}</strong><small className="cell-note">{event.notes}</small></td><td>{event.farmName}</td><td>{labels[event.type]??event.type}</td><td>{event.product??"—"}<small className="cell-note">{event.dose}</small></td><td>{event.animalCount??"—"}</td><td><span className={`status-pill ${event.status}`}>{event.status}</span></td></tr>)}</tbody></table></div></section>
    <section className="table-section"><div className="table-section-heading"><div><span className="eyebrow">REPRODUCCIÓN</span><h2>Historial y planificación reproductiva</h2></div><span>{reproduction.length} registros</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Fecha</th><th>Evento</th><th>Campo</th><th>Animales</th><th>Resultado / planificación</th><th>Observaciones</th></tr></thead><tbody>{reproduction.map(event=><tr key={event.id}><td>{fmt.format(new Date(`${event.eventDate}T12:00:00`))}</td><td><strong>{labels[event.type]??event.type}</strong></td><td>{event.farmName}</td><td>{event.animalCount??"—"}</td><td>{event.result??"—"}</td><td>{event.notes??"—"}</td></tr>)}</tbody></table></div></section>
    {creating&&<CreateHealthDialog farms={selectedFarm?farms.filter(farm=>farm.id===selectedFarm.id):farms} onClose={()=>setCreating(false)} onCreated={()=>{setCreating(false);void load()}}/>}
  </section>
}

function CreateHealthDialog({farms,onClose,onCreated}:{farms:Array<{id:string;name:string}>;onClose():void;onCreated():void}) {
  const [farmId,setFarmId]=useState(farms[0]?.id??""); const [type,setType]=useState("vacunacion"); const [title,setTitle]=useState(""); const [scheduledOn,setDate]=useState(new Date().toISOString().slice(0,10)); const [count,setCount]=useState(""); const [product,setProduct]=useState(""); const [dose,setDose]=useState(""); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null)
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError(null);try{await healthService.create({farmId,title,type,scheduledOn,animalCount:Number(count)||undefined,product,dose,notes});onCreated()}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos guardar.")}finally{setSaving(false)}}
  return <div className="dialog-backdrop"><form className="dialog-card compact-dialog" onSubmit={submit}><div className="dialog-header"><div><span className="eyebrow">SANIDAD Y REPRODUCCIÓN</span><h2>Nueva actividad</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="Cerrar"><X/></button></div><div className="form-grid"><label className="span-2">Campo<select value={farmId} onChange={event=>setFarmId(event.target.value)}>{farms.map(farm=><option key={farm.id} value={farm.id}>{farm.name}</option>)}</select></label><label>Tipo<select value={type} onChange={event=>setType(event.target.value)}><optgroup label="Sanidad"><option value="vacunacion">Vacunación</option><option value="tratamiento">Tratamiento</option><option value="diagnostico">Diagnóstico</option><option value="desparasitacion">Desparasitación</option><option value="control">Control</option></optgroup><optgroup label="Reproducción"><option value="servicio">Servicio</option><option value="inseminacion">Inseminación</option><option value="tacto">Tacto</option><option value="parto">Parto</option><option value="destete">Destete</option></optgroup></select></label><label>Fecha<input required type="date" value={scheduledOn} onChange={event=>setDate(event.target.value)}/></label><label className="span-2">Actividad o resultado<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Cantidad de animales<input type="number" min="1" value={count} onChange={event=>setCount(event.target.value)}/></label><label>Producto<input value={product} onChange={event=>setProduct(event.target.value)}/></label><label>Dosis<input value={dose} onChange={event=>setDose(event.target.value)}/></label><label className="span-2">Observaciones<textarea rows={3} value={notes} onChange={event=>setNotes(event.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Guardando…":"Guardar actividad"}</button></div></form></div>
}
