import { FormEvent, useState } from "react"
import { X } from "lucide-react"
import { agroService, type FarmListItem } from "@/services/agro.service"

export function CreateMovementDialog({ farms, initialOperation, onClose, onCreated }: { farms: FarmListItem[]; initialOperation?:string; onClose():void; onCreated():void }) {
  const [farmId,setFarmId]=useState(farms[0]?.id??""); const [operation,setOperation]=useState(initialOperation??"traslado"); const [occurredOn,setOccurredOn]=useState(new Date().toISOString().slice(0,10)); const [animalCount,setAnimalCount]=useState(""); const [weight,setWeight]=useState(""); const [notes,setNotes]=useState(""); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null)
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError(null);try{await agroService.createLivestockMovement({farmId,operation,occurredOn,animalCount:Number(animalCount),totalWeightKg:weight?Number(weight):undefined,notes});onCreated()}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos registrar el movimiento.")}finally{setSaving(false)}}
  return <div className="dialog-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><form className="dialog-card compact-dialog" onSubmit={submit} role="dialog" aria-modal="true"><div className="dialog-header"><div><span className="eyebrow">HACIENDA</span><h2>Registrar movimiento</h2></div><button type="button" className="icon-button" onClick={onClose}><X/></button></div><div className="form-grid"><label className="span-2">Campo<select required value={farmId} onChange={e=>setFarmId(e.target.value)}>{farms.map(farm=><option value={farm.id} key={farm.id}>{farm.name}</option>)}</select></label><label>Tipo<select value={operation} onChange={e=>setOperation(e.target.value)}><option value="nacimiento">Nacimiento</option><option value="compra">Compra</option><option value="venta">Venta</option><option value="muerte">Muerte</option><option value="traslado">Traslado</option><option value="cambio_categoria">Cambio de categoría</option><option value="ajuste">Pesaje / ajuste</option></select></label><label>Fecha<input type="date" required value={occurredOn} onChange={e=>setOccurredOn(e.target.value)}/></label><label>Cantidad de cabezas<input type="number" min="1" required value={animalCount} onChange={e=>setAnimalCount(e.target.value)}/></label><label>Peso total (kg)<input type="number" min="0" step="0.1" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label className="span-2">Observaciones<textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)}/></label></div>{error&&<div className="form-error">{error}</div>}<div className="dialog-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?"Guardando…":"Guardar borrador"}</button></div></form></div>
}
