import { useMemo, useState } from "react"
import { Check, ChevronLeft, ChevronRight, FileUp, X } from "lucide-react"
import { FIELD_CATALOG, type SystemField } from "@/features/livestock/import-engine/field-catalog"
import { mappingSignature, suggestMapping, type ColumnMapping } from "@/features/livestock/import-engine/mapper"
import { inferFilenameContext, parseGallagherCsv, remapLivestockCsv, type FilenameContext, type FilenameContextDecision, type GallagherRow, type ParsedLivestockImport } from "@/services/livestock-registry.service"
import { livestockImportService, type DraftGroupDecision, type HerdOption, type SessionMode, type SessionTypeOption, type WorkSessionOption } from "@/services/livestock-import.service"
import "@/features/livestock/livestock-import.css"
import "@/features/livestock/livestock-import-ux.css"

type Step="file"|"mapping"|"context"|"preview"|"done"
const emptyConfirmed:FilenameContextDecision["confirmed"]={categoryName:false,herdName:false,reproductiveStatus:false,calvingSeason:false,eventType:false,probableDate:false,period:false}
const contextFields:[keyof FilenameContextDecision["confirmed"],string][]=[["categoryName","Categoría"],["eventType","Acción"],["probableDate","Fecha"],["period","Período"],["reproductiveStatus","Información reproductiva"]]
function normalized(value:string){return value.trim().toLocaleLowerCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\s+/g," ")}
function exactName(value:string){return value.trim().toLocaleLowerCase("es").replace(/\s+/g," ")}
function similarity(source:string,target:string){const a=new Set(normalized(source).split(" ")),b=new Set(normalized(target).split(" ")),shared=[...a].filter(value=>b.has(value)).length;return shared/Math.max(a.size,b.size,1)}
function needsColumnReview(headers:string[],mapping:ColumnMapping){const active=headers.map(header=>mapping[header]).filter(field=>field!=="ignore");return headers.some(header=>mapping[header]==="ignore")||new Set(active).size!==active.length}

export function LivestockImportDialog({farmId,farmName,onClose,onDone,onReviewSession}:{farmId:string;farmName:string;onClose():void;onDone():void;onReviewSession():void}){
 const[step,setStep]=useState<Step>("file"),[reviewReturn,setReviewReturn]=useState<"file"|"context">("file"),[file,setFile]=useState<File|null>(null),[parsed,setParsed]=useState<ParsedLivestockImport|null>(null),[mapping,setMapping]=useState<ColumnMapping>({}),[autoMapping,setAutoMapping]=useState<ColumnMapping>({}),[rows,setRows]=useState<GallagherRow[]>([])
 const[context,setContext]=useState<FilenameContext|null>(null),[confirmed,setConfirmed]=useState(emptyConfirmed),[mode,setMode]=useState<SessionMode>("new"),[sessions,setSessions]=useState<WorkSessionOption[]>([]),[sessionTypes,setSessionTypes]=useState<SessionTypeOption[]>([]),[herds,setHerds]=useState<HerdOption[]>([])
 const[existingSessionId,setExistingSessionId]=useState(""),[sessionDate,setSessionDate]=useState(""),[sessionType,setSessionType]=useState(""),[templateId,setTemplateId]=useState<string>(),[templateName,setTemplateName]=useState(""),[groupDecisions,setGroupDecisions]=useState<Record<string,DraftGroupDecision>>({})
 const[duplicate,setDuplicate]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[result,setResult]=useState<Record<string,unknown>|null>(null)
 const ignored=Object.values(mapping).filter(value=>value==="ignore").length
 const activeColumnFields=Object.values(mapping).filter(value=>value!=="ignore"),hasColumnConflict=new Set(activeColumnFields).size!==activeColumnFields.length
 const columnsNeedReview=parsed?needsColumnReview(parsed.document.headers,mapping):false
 const counts=useMemo(()=>Object.fromEntries(["NUEVO","EXISTENTE","ACTUALIZAR","REVERTIDO","CONFLICTO","ERROR","DUPLICADO"].map(status=>[status,rows.filter(row=>row.status===status).length])),[rows])
 const eventCounts=useMemo(()=>{const events=rows.flatMap(row=>row.externalEvents);return{new:events.filter(event=>event.status==="NUEVO").length,existing:events.filter(event=>event.status==="EXISTENTE").length,uninterpreted:rows.reduce((total,row)=>total+row.uninterpretedValues.length,0)}},[rows])
 const customValues=useMemo(()=>{const grouped=new Map<string,Set<string>>();rows.flatMap(row=>row.uninterpretedValues).forEach(item=>grouped.set(item.field,new Set([...(grouped.get(item.field)??[]),item.value])));return[...grouped].map(([field,values])=>({field,values:[...values]}))},[rows])
 const groups=useMemo(()=>[...new Set(rows.map(row=>row.draftGroup.trim()).filter(Boolean))],[rows])
 const unresolvedGroups=groups.filter(group=>!groupDecisions[group])
 const valid=(counts.NUEVO??0)+(counts.EXISTENTE??0)+(counts.ACTUALIZAR??0)+rows.filter(row=>row.status==="REVERTIDO"&&row.reactivate).length
 const problems=(counts.CONFLICTO??0)+(counts.ERROR??0)+(counts.DUPLICADO??0)+rows.filter(row=>row.status==="REVERTIDO"&&!row.reactivate).length
 const dateRequired=rows.some(row=>!row.eventDate)

 function initialDecisions(nextRows:GallagherRow[],options:HerdOption[]){return Object.fromEntries([...new Set(nextRows.map(row=>row.draftGroup.trim()).filter(Boolean))].map(group=>{const exact=options.find(herd=>exactName(herd.name)===exactName(group));return[group,exact?{mode:"existing",herd_id:exact.id,suggested:true}:{mode:"ignore"}]})) as Record<string,DraftGroupDecision>}
 async function choose(next:File){setBusy(true);setError("");setDuplicate("");try{const initial=await parseGallagherCsv(next),signature=mappingSignature(initial.document.headers),automatic=suggestMapping(initial.document.headers);const[template,workSessions,types,herdOptions,prior]=await Promise.all([livestockImportService.mappingTemplate("gallagher",signature),livestockImportService.workSessions(farmId),livestockImportService.sessionTypes(),livestockImportService.herds(farmId),livestockImportService.duplicateImport(farmId,initial.document.hash)]);const activeMapping=template?.mapping??automatic,nextRows=remapLivestockCsv(initial.document,activeMapping,initial.detectedDate?.slice(0,10)??"");setFile(next);setParsed(initial);setMapping(activeMapping);setAutoMapping(automatic);setRows(nextRows);setContext(inferFilenameContext(next.name));setConfirmed(emptyConfirmed);setSessionDate(initial.detectedDate?.slice(0,10)??inferFilenameContext(next.name).probableDate);setSessions(workSessions);setSessionTypes(types);setHerds(herdOptions);setSessionType(types.find(type=>type.name.toLowerCase()==="otro")?.name??types[0]?.name??"");setGroupDecisions(initialDecisions(nextRows,herdOptions));setTemplateId(template?.id);setTemplateName(template?.name??"");if(prior)setDuplicate(`Este archivo ya fue importado como ${prior.filename}.`);const review=initial.format==="generic"&&needsColumnReview(initial.document.headers,activeMapping);setReviewReturn(review?"file":"context");setStep(review?"mapping":"context")}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos leer el archivo.")}finally{setBusy(false)}}
 function remap(next:ColumnMapping,date=sessionDate){if(!parsed)return;const nextRows=remapLivestockCsv(parsed.document,next,date);setRows(nextRows);setGroupDecisions(current=>({...initialDecisions(nextRows,herds),...current}))}
 function updateMapping(header:string,field:SystemField){const next={...mapping,[header]:field};setMapping(next);remap(next)}
 async function preparePreview(){if(!parsed)return;setBusy(true);setError("");try{const classified=await livestockImportService.classify(farmId,remapLivestockCsv(parsed.document,mapping,sessionDate));setRows(await livestockImportService.classifyExternalEvents(farmId,classified));setStep("preview")}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos preparar el preview.")}finally{setBusy(false)}}
 async function confirmImport(){if(!file||!parsed||!context)return;setBusy(true);setError("");try{const response=await livestockImportService.confirm({farmId,provider:"gallagher",file,document:parsed.document,mapping,rows,filenameDecision:{values:context,original:inferFilenameContext(file.name),confirmed},sessionMode:mode,existingSessionId:mode==="existing"?existingSessionId:undefined,sessionType,sessionDate,mappingTemplateId:templateId,draftGroupDecisions:groupDecisions});if(templateName.trim()&&!templateId)await livestockImportService.saveMapping("gallagher",templateName.trim(),mappingSignature(parsed.document.headers),parsed.document.headers,mapping);setResult((response??{}) as Record<string,unknown>);setStep("done")}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos importar.")}finally{setBusy(false)}}
 async function confirmSession(){const id=String(result?.work_session_id??"");if(!id)return;setBusy(true);try{await livestockImportService.confirmSession(id);onDone()}catch(reason){setError(reason instanceof Error?reason.message:"No pudimos confirmar la jornada.")}finally{setBusy(false)}}
 const canPreview=valid>0&&!duplicate&&!unresolvedGroups.length&&(!dateRequired||Boolean(sessionDate))&&(mode!=="existing"||Boolean(existingSessionId))&&(mode!=="new"||Boolean(sessionDate&&sessionType))

 return <div className="dialog-backdrop"><article className="dialog-card livestock-import-dialog"><div className="dialog-header"><div><span className="eyebrow">GALLAGHER · {farmName.toUpperCase()}</span><h2>Importar información ganadera</h2></div><button className="icon-button" onClick={onClose}><X/></button></div>
  <div className="import-steps main-import-steps">{(["file","context","preview"] as Step[]).map((item,index)=><span className={step===item||item==="file"&&step==="mapping"?"active":""} key={item}>{index+1}. {item==="file"?"Archivo":item==="context"?"Jornada y rodeos":"Confirmar"}</span>)}</div>
  {step==="file"&&<label className="inventory-entry-panel"><div><strong>Seleccionar CSV de Gallagher</strong><p>El análisis no escribe datos.</p></div><input type="file" accept=".csv,text/csv" onChange={event=>event.target.files?.[0]&&void choose(event.target.files[0])}/><span className="file-picker-button"><FileUp size={16}/> Seleccionar archivo</span></label>}
  {step==="context"&&<div className="detected-columns-banner"><span><Check size={16}/><strong>{parsed?.format==="animal_history"?`Detectamos un Animal History con ${rows.length} animales únicos${parsed.externalSessions.length?` · ${parsed.externalSessions.length} sesión(es) Gallagher`:""}`:parsed?.format==="session_export"?rows.length?`Detectamos una sesión Gallagher con ${rows.length} animales`:`La sesión Gallagher no contiene animales`:columnsNeedReview?`Revisaste la información de las ${parsed?.document.headers.length??0} columnas`:`Detectamos correctamente las ${parsed?.document.headers.length??0} columnas del archivo`}</strong></span><button onClick={()=>{setReviewReturn("context");setStep("mapping")}}>Revisar columnas</button></div>}
  {step==="mapping"&&parsed&&parsed.format!=="generic"&&<section className="import-stage"><h3>Información detectada</h3><p>Gallagher permite personalizar cada exportación. Reconocimos la información estándar y separamos los campos propios del establecimiento.</p><div className="adapter-column-summary"><div><strong>Reconocido automáticamente</strong><span>Caravana visual</span><span>Caravana electrónica (EID)</span><span>Fecha y hora del registro</span><span>Notas y datos ganaderos conocidos</span></div><div><strong>Campos personalizados Gallagher</strong>{customValues.length?customValues.map(item=><span key={item.field}><b>{item.field}</b><small>Valores: {item.values.slice(0,6).join(", ")}{item.values.length>6?"…":""} · No se importará hasta definir su significado.</small></span>):<span>No encontramos valores personalizados pendientes.</span>}</div></div></section>}
  {step==="mapping"&&parsed&&parsed.format==="generic"&&<section className="import-stage"><h3>Información detectada</h3><p>Reconocimos qué información contiene cada columna. Podés corregirla o elegir “Ignorar esta columna”.</p><div className="column-purpose-note">En esta pantalla sólo identificamos el contenido. Los rodeos se deciden después, en “Jornada y rodeos”.</div><div className="mapping-grid">{parsed.document.headers.map(header=>{const field=mapping[header]??"ignore",automatic=autoMapping[header]??"ignore",duplicate=field!=="ignore"&&Object.values(mapping).filter(value=>value===field).length>1,status=field==="ignore"&&automatic==="ignore"?"unknown":duplicate||field!==automatic?"review":"recognized";return <div className="mapping-row friendly-mapping-row" key={header}><div><strong>{header}</strong><small>{parsed.document.rows[0]?.[header]||"Sin información de ejemplo"}</small></div><ChevronRight size={16}/><div><select value={field} onChange={event=>updateMapping(header,event.target.value as SystemField)}>{FIELD_CATALOG.map(option=><option value={option.key} key={option.key}>{option.key==="electronicId"?"Caravana electrónica (EID)":option.key==="eventDate"?"Fecha del registro":option.label}</option>)}</select><span className={`column-recognition ${status}`}>{status==="recognized"?"✓ Reconocido automáticamente":status==="review"?"! Necesita revisión":"? No reconocido"}</span>{field==="draftGroup"&&<small>Esto no crea ni asigna un rodeo todavía.</small>}</div></div>})}</div>{ignored>0&&<p className="mapping-note">{ignored} columna(s) quedarán sin importar. Esto no impide continuar después de revisarlas.</p>}</section>}
  {step==="context"&&context&&<section className="import-stage"><h3>Jornada, contexto y rodeos</h3><div className="session-mode-grid">{(["new","existing","none"] as SessionMode[]).map(value=><button key={value} className={mode===value?"choice-card active":"choice-card"} onClick={()=>setMode(value)}><strong>{value==="new"?"Crear jornada":value==="existing"?"Asociar a existente":"Sin jornada"}</strong><span>{value==="new"?"Quedará en borrador.":value==="existing"?"No modifica su estado.":"Sólo animales y eventos."}</span></button>)}</div>{mode==="existing"&&<label className="form-field"><span>Jornada existente</span><select value={existingSessionId} onChange={event=>setExistingSessionId(event.target.value)}><option value="">Seleccionar…</option>{sessions.map(session=><option value={session.id} key={session.id}>{session.date} · {session.title}</option>)}</select></label>}{mode==="new"&&<label className="form-field"><span>Tipo de jornada</span><select value={sessionType} onChange={event=>setSessionType(event.target.value)}>{sessionTypes.map(type=><option value={type.name} key={type.id}>{type.name}</option>)}</select></label>}<label className="form-field"><span>Fecha para filas sin fecha</span><input type="date" value={sessionDate} onChange={event=>{setSessionDate(event.target.value);remap(mapping,event.target.value)}}/><small>Nunca se reemplaza por la fecha de importación.</small></label>
   <div className="context-panel"><strong>Contexto inferido del nombre</strong>{contextFields.map(([key,label])=>{const value=String(context[key]??"");return value?<label className="context-choice" key={key}><input type="checkbox" checked={confirmed[key]} disabled={key==="herdName"&&groups.length>0} onChange={event=>setConfirmed(current=>({...current,[key]:event.target.checked}))}/><span><strong>{label}</strong><input value={value} disabled={key==="herdName"&&groups.length>0} onChange={event=>setContext(current=>current?{...current,[key]:event.target.value}:current)}/></span></label>:null})}</div>
   {groups.length>0&&<div className="draft-group-panel"><div><strong>Decisiones para Draft Group</strong><small>Ningún rodeo se crea sin confirmación.</small></div>{groups.map(group=>{const decision=groupDecisions[group],suggestions=herds.filter(herd=>normalized(herd.name)!==normalized(group)).map(herd=>({...herd,score:similarity(group,herd.name)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score).slice(0,3);return <div className="draft-group-card" key={group}><strong>{group}</strong>{decision?.mode==="existing"&&decision.suggested&&<small>Coincidencia exacta preseleccionada; revisala antes de importar.</small>}<select value={decision?.mode==="existing"?`existing:${decision.herd_id}`:decision?.mode??""} onChange={event=>{const[value,id]=event.target.value.split(":");setGroupDecisions(current=>({...current,[group]:value==="existing"?{mode:"existing",herd_id:id}:value==="create"?{mode:"create",name:group,confirmed:false}:{mode:"ignore"}}))}}><option value="ignore">No asignar rodeo</option>{herds.map(herd=><option value={`existing:${herd.id}`} key={herd.id}>Asociar a {herd.name}</option>)}<option value="create">Crear un rodeo nuevo…</option></select>{decision?.mode==="create"&&<label><input value={decision.name??group} onChange={event=>setGroupDecisions(current=>({...current,[group]:{...decision,name:event.target.value}}))}/><span><input type="checkbox" checked={Boolean(decision.confirmed)} onChange={event=>setGroupDecisions(current=>({...current,[group]:{...decision,confirmed:event.target.checked}}))}/> Confirmo crear este rodeo</span></label>}{decision?.mode!=="existing"&&suggestions.length>0&&<small>Sugerencias: {suggestions.map(item=>item.name).join(", ")}. No se aplican automáticamente.</small>}</div>})}</div>}
  </section>}
  {step==="preview"&&<section className="import-stage"><h3>Confirmar impacto</h3><div className="record-summary"><span><strong>{rows.length}</strong> animales únicos</span><span><strong>{counts.NUEVO??0}</strong> animales nuevos</span><span><strong>{(counts.EXISTENTE??0)+(counts.ACTUALIZAR??0)}</strong> encontrados por EID</span><span><strong>{eventCounts.new}</strong> eventos nuevos</span><span><strong>{eventCounts.existing}</strong> eventos existentes</span><span><strong>{eventCounts.uninterpreted}</strong> valores sin interpretar</span><span><strong>{problems}</strong> conflictos/errores</span></div>{eventCounts.existing>0&&<div className="mapping-note">Los eventos existentes no se crearán nuevamente. Esta importación registrará que volvieron a aparecer.</div>}{groups.length>0&&<div className="preview-decisions">{groups.map(group=><span key={group}><strong>{group}</strong> → {groupDecisions[group]?.mode==="existing"?herds.find(herd=>herd.id===groupDecisions[group].herd_id)?.name:groupDecisions[group]?.mode==="create"?`Crear “${groupDecisions[group].name}”`:"Sin rodeo"}</span>)}</div>}<div className="table-wrap preview-table"><table className="data-table"><thead><tr><th>Fila</th><th>Caravana</th><th>EID</th><th>Fecha</th><th>Eventos nuevos</th><th>Eventos existentes</th><th>Estado</th></tr></thead><tbody>{rows.slice(0,200).map(row=><tr key={row.rowNumber}><td>{row.rowNumber}</td><td>{row.tagNumber||"—"}</td><td>{row.electronicIdRaw||"—"}</td><td>{row.eventDate.slice(0,10)||"—"}</td><td>{row.externalEvents.filter(event=>event.status==="NUEVO").length}</td><td>{row.externalEvents.filter(event=>event.status==="EXISTENTE").length}</td><td><span className={`decision-signal ${row.status==="REVERTIDO"?"watch":"good"}`}>{row.status}</span>{row.status==="REVERTIDO"&&<label className="reactivate-choice"><input type="checkbox" checked={Boolean(row.reactivate)} onChange={event=>setRows(current=>current.map(item=>item.rowNumber===row.rowNumber?{...item,reactivate:event.target.checked}:item))}/> Reactivar este animal</label>}<small>{row.message}</small></td></tr>)}</tbody></table></div></section>}
  {step==="done"&&<section className="import-stage import-success"><Check size={34}/><h3>Importación completada</h3>{mode==="new"&&result?.work_session_id?<><p>La jornada quedó guardada como borrador. Podés revisarla antes de confirmarla.</p><div className="imported-session-summary"><span><small>Jornada</small><strong>{sessionType||"Jornada ganadera"}</strong></span><span><small>Fecha</small><strong>{sessionDate||"Sin fecha"}</strong></span><span><small>Animales importados</small><strong>{valid}</strong></span></div><div className="import-success-actions"><button className="primary-button" onClick={onReviewSession}>Revisar jornada</button><button className="secondary-button" disabled={busy} onClick={()=>void confirmSession()}>{busy?"Confirmando…":"Confirmar ahora"}</button><button className="text-button" disabled={busy} onClick={onDone}>Cerrar y confirmar después</button></div></>:<><p>La información del archivo quedó registrada correctamente.</p><button className="primary-button" onClick={onDone}>Finalizar</button></>}</section>}
  {duplicate&&<div className="form-error">{duplicate}</div>}{error&&<div className="form-error">{error}</div>}
  {step!=="file"&&step!=="done"&&<div className="dialog-actions"><button className="secondary-button" onClick={()=>setStep(step==="mapping"?reviewReturn:step==="context"?"file":"context")}><ChevronLeft size={16}/> Atrás</button>{step==="mapping"&&<button className="primary-button" disabled={hasColumnConflict} onClick={()=>setStep("context")}>Continuar</button>}{step==="context"&&<button className="primary-button" disabled={!canPreview||busy||groups.some(group=>groupDecisions[group]?.mode==="create"&&!groupDecisions[group]?.confirmed)} onClick={()=>void preparePreview()}>Continuar a confirmar</button>}{step==="preview"&&<button className="primary-button" disabled={!canPreview||busy||problems>0} onClick={()=>void confirmImport()}>{busy?"Importando…":"Confirmar importación"}</button>}</div>}
 </article></div>
}
