create type public.livestock_destination as enum('vender','recriar','terminar');
create table public.livestock_decisions(id uuid primary key default gen_random_uuid(),farm_id uuid not null references public.farms(id)on delete cascade,campaign_id uuid not null references public.campaigns(id)on delete cascade,source_cycle_id uuid references public.livestock_cycles(id)on delete set null,herd_name text not null,decision_date date not null default current_date,heads integer not null check(heads>0),current_weight_kg numeric(12,2)not null check(current_weight_kg>0),current_price_ars_kg numeric(14,2)not null check(current_price_ars_kg>0),sale_cost_percent numeric(6,3)not null default 3 check(sale_cost_percent between 0 and 25),freight_ars_head numeric(14,2)not null default 0,notes text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.livestock_decision_options(id uuid primary key default gen_random_uuid(),decision_id uuid not null references public.livestock_decisions(id)on delete cascade,destination public.livestock_destination not null,days_to_sale integer not null default 0 check(days_to_sale>=0),target_weight_kg numeric(12,2)not null check(target_weight_kg>0),future_price_ars_kg numeric(14,2)not null check(future_price_ars_kg>0),mortality_percent numeric(6,3)not null default 0 check(mortality_percent between 0 and 20),feed_cost_ars_head numeric(16,2)not null default 0,pasture_cost_ars_head numeric(16,2)not null default 0,health_cost_ars_head numeric(16,2)not null default 0,other_cost_ars_head numeric(16,2)not null default 0,capital_rate_monthly_percent numeric(8,4)not null default 0 check(capital_rate_monthly_percent>=0),required_hectares numeric(12,2)not null default 0,unique(decision_id,destination));
alter table public.livestock_decisions enable row level security;alter table public.livestock_decision_options enable row level security;
create policy livestock_decisions_access on public.livestock_decisions for all to authenticated using(public.can_access_farm(farm_id))with check(public.can_manage_farm(farm_id)and created_by=auth.uid());
create policy livestock_options_access on public.livestock_decision_options for all to authenticated using(exists(select 1 from public.livestock_decisions d where d.id=decision_id and public.can_access_farm(d.farm_id)))with check(exists(select 1 from public.livestock_decisions d where d.id=decision_id and public.can_manage_farm(d.farm_id)));
create view public.livestock_destination_analysis with(security_invoker=true)as
select o.id,d.id decision_id,d.farm_id,f.name farm_name,d.campaign_id,c.name campaign_name,d.herd_name,d.decision_date,d.heads,d.current_weight_kg,d.current_price_ars_kg,o.destination,o.days_to_sale,o.target_weight_kg,o.future_price_ars_kg,o.mortality_percent,o.required_hectares,
(d.heads*d.current_weight_kg*d.current_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*d.freight_ars_head)::numeric(18,2)sell_now_net_ars,
(d.heads*(1-o.mortality_percent/100)*o.target_weight_kg*o.future_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*(1-o.mortality_percent/100)*d.freight_ars_head)::numeric(18,2)future_net_ars,
(d.heads*(o.feed_cost_ars_head+o.pasture_cost_ars_head+o.health_cost_ars_head+o.other_cost_ars_head))::numeric(18,2)direct_incremental_cost_ars,
(case when o.days_to_sale=0 then 0 else(d.heads*d.current_weight_kg*d.current_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*d.freight_ars_head)*(power(1+o.capital_rate_monthly_percent/100,o.days_to_sale/30.0)-1)end)::numeric(18,2)capital_cost_ars,
(case when o.destination='vender'then 0 else d.heads*(1-o.mortality_percent/100)*o.target_weight_kg*o.future_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*(1-o.mortality_percent/100)*d.freight_ars_head-d.heads*d.current_weight_kg*d.current_price_ars_kg*(1-d.sale_cost_percent/100)+d.heads*d.freight_ars_head-d.heads*(o.feed_cost_ars_head+o.pasture_cost_ars_head+o.health_cost_ars_head+o.other_cost_ars_head)-(case when o.days_to_sale=0 then 0 else(d.heads*d.current_weight_kg*d.current_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*d.freight_ars_head)*(power(1+o.capital_rate_monthly_percent/100,o.days_to_sale/30.0)-1)end)end)::numeric(18,2)decision_value_ars,
(case when o.destination='vender'then d.current_price_ars_kg else(d.heads*d.current_weight_kg*d.current_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*d.freight_ars_head+d.heads*(o.feed_cost_ars_head+o.pasture_cost_ars_head+o.health_cost_ars_head+o.other_cost_ars_head)+(case when o.days_to_sale=0 then 0 else(d.heads*d.current_weight_kg*d.current_price_ars_kg*(1-d.sale_cost_percent/100)-d.heads*d.freight_ars_head)*(power(1+o.capital_rate_monthly_percent/100,o.days_to_sale/30.0)-1)end)+d.heads*(1-o.mortality_percent/100)*d.freight_ars_head)/(d.heads*(1-o.mortality_percent/100)*o.target_weight_kg*(1-d.sale_cost_percent/100))end)::numeric(14,2)break_even_price_ars_kg,
(case when o.required_hectares>0 then(d.heads*(1-o.mortality_percent/100)*o.target_weight_kg-d.heads*d.current_weight_kg)/o.required_hectares else 0 end)::numeric(12,2)additional_kg_ha
from public.livestock_decision_options o join public.livestock_decisions d on d.id=o.decision_id join public.farms f on f.id=d.farm_id join public.campaigns c on c.id=d.campaign_id;
grant select on public.livestock_destination_analysis to authenticated;
